# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'PIL',
        'PIL.Image',
        'win32event',
        'win32api',
        'win32gui',
        'winerror',
        'watchdog',
        'watchdog.observers',
        'watchdog.events',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pystray._appindicator',
        'pystray._darwin',
        'pystray._gtk',
        'pystray._xorg',
        'pystray._util.gtk',
        'pystray._util.notify_dbus',
        'plyer',
        'plyer.platforms',
        'plyer.platforms.win',
        'win10toast_click',
        'win11toast',
        'winrt',
        'winrt.runtime',
        'winrt.windows.foundation',
        'winrt.windows.foundation.collections',
        'winrt.windows.data.xml.dom',
        'winrt.windows.ui.notifications',
        'gi',
        'gi.repository',
        'Xlib',
        'Xlib.XK',
        'Xlib.threaded',
        'AppKit',
        'Foundation',
        'objc',
        'PyObjCTools',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='LocalSendClipboardPlugin',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
